title: Chris Buckley
description: AppleScript snippet to play chrome://dino

url: https://cmbuckley.co.uk
baseurl: /dino

repository: cmbuckley/dino
remote_theme: "cmbuckley/cmbuckley.github.io"

plugins:
  - jekyll-github-metadata
  - jekyll-remote-theme

markdown: kramdown
highlighter: rouge

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
